import pandas as pd


def load_esteiras():
    # Carregar as esteiras a partir de um arquivo ou definir manualmente
    df_esteiras = pd.DataFrame(columns=['Esteiras'])
    df_esteiras['Esteiras'] = ['02.03 AGUARDANDO PROCESSAMENTO CARTAO', '11 FORMALIZACAO', '11 FORMALIZAAAO', '09.0 PAGO', 'RISCO DA OPERACAO - OBITO',
                                '11 FORMALIZAAÂAÂO', '14.0 RISCO DA OPERACAO - OBITO', 'RISCO DA OPERACAO-DEMAIS SITUACOES', '11.PROBLEMAS DE AVERBACAO',
                                '10.7.0 INGRESSAR COM PROCESSO OU ACAO JURIDICO', '10.7 CONTRATO NAO AVERBADO - AGUARDANDO RESOLUCAO', '15.0\tRISCO DA OPERACAO-DEMAIS SITUACOES',
                                '11.1 CONTRATO FISICO ENVIADO AO BANCO', '07.0 QUITACAO  ENVIO DE CESSAO', '07.2 TED DEVOLVIDA PAGAMENTO AO CLIENTE',
                                '07.2 TED DEVOLVIDA A PAGAMENTO AO CLIENTE', '99 CARTAO UTILIZADO', '07.1.1 QUITACAO - CORRECAO DE CCB', 'RISCO DA OPERAAAO-DEMAIS SITUAAAES',
                                '10.7 CONTRATO NAO AVERBADO - AGUARDANDO RESOLUAAO', '11 FORMALIZAAÂ‡AÂƒO', '10.5 AGUARDANDO AVERBACAO COMPRA OUTROS CONVENIOS',
                                '07.2 TED DEVOLVIDA AÂÂ PAGAMENTO AO CLIENTE', 'RISCO DA OPERAAÂAÂO-DEMAIS SITUAAÂAÂES', '10.7 CONTRATO NAÂO AVERBADO - AGUARDANDO RESOLUAÂAÂO',
                                'RISCO DA OPERACAO - DEMAIS SITUACOES', '15.0 RISCO DA OPERACAO - DEMAIS SITUACOES', 'INTEGRADO', '07.1 AÂ– QUITACAO AÂ– PAGAMENTO AO CLIENTE',
                                '15.0 RISCO DA OPERACAO-DEMAIS SITUACOES', 'RISCO DA OPERACAO - DEMAIS SITUACOEES', '07.0 QUITACAO  ENVIO DE CESSAO', '10.7.0 INGRESSAR COM PROCESSO OU AAAO JURIDICO',
                                'INT', 'CONFERE LASTRO', '09.0 - APOSENTADORIA IGEPREV - AGUARDANDO AVERBACAO', '09.1 - APOSENTADORIA IGEPREV - AVERB. TOTAL', '09.2 - APOSENTADORIA IGEPREV - AVERB. PARCIAL',
                                '11.2  DETERMINACAO JUDICIAL', 'LIBERACAO FINANCEIRA', 'ENVIA PAGAMENTO', 'M NEGATIVA / SEM MARGEM', 'PENDENTE TED DEVOLVIDA', 'AGD PROCESSAMENTO FOLHA',
                                '14.0 RISCO DA OPERAÇÃO - ÓBITO'
                                ]

    return df_esteiras['Esteiras'].tolist()